# Generated by Django 4.1.3 on 2022-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20221101_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama',
            new_name='nama_gundam',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='kodebrng',
            new_name='seri_gundam',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='waktu_posting',
        ),
    ]
