# Generated by Django 4.1.3 on 2022-11-24 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_rename_nama_barang_nama_gundam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='seri_gundam',
            new_name='kodebrng',
        ),
        migrations.RenameField(
            model_name='barang',
            old_name='nama_gundam',
            new_name='nama',
        ),
    ]
