# Generated by Django 4.1.3 on 2022-11-24 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_rename_seri_gundam_barang_kodebrng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama',
            new_name='nama_barang',
        ),
    ]
